# Generated by Django 4.2.1 on 2023-06-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('ctitle', models.CharField(max_length=50, null=True)),
                ('ccode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('insid', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100, null=True)),
                ('collegedean', models.CharField(max_length=100, null=True)),
                ('collegeid', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ctitle', models.CharField(max_length=50, null=True)),
                ('ccode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cr_hr', models.IntegerField(null=True)),
                ('dep', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('semi', models.CharField(max_length=10, null=True)),
                ('lec_hr', models.IntegerField(null=True)),
                ('lab_hr', models.IntegerField(null=True)),
                ('prerequisite', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cummlative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=25, null=True)),
                ('dep', models.CharField(max_length=25, null=True)),
                ('prcredit', models.IntegerField(null=True)),
                ('prgp', models.IntegerField(null=True)),
                ('prgrade', models.IntegerField(null=True)),
                ('semicredit', models.IntegerField(null=True)),
                ('semigp', models.IntegerField(null=True)),
                ('semigrade', models.IntegerField(null=True)),
                ('cumcredit', models.IntegerField(null=True)),
                ('cumgp', models.IntegerField(null=True)),
                ('cumgrade', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(max_length=25, null=True)),
                ('depid', models.CharField(max_length=10, null=True)),
                ('dephead', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=1000, null=True)),
                ('dep', models.CharField(max_length=1000, null=True)),
                ('inst', models.CharField(max_length=1000, null=True)),
                ('student', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=25, null=True)),
                ('ctitle', models.CharField(max_length=25, null=True)),
                ('ccode', models.CharField(max_length=10, null=True)),
                ('cr_hr', models.IntegerField(null=True)),
                ('dep', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('semi', models.CharField(max_length=10, null=True)),
                ('noGr', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=1, null=True)),
                ('grpoint', models.IntegerField(null=True)),
                ('approval', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('insid', models.CharField(max_length=10, null=True)),
                ('dep', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('regid', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=100, null=True)),
                ('mName', models.CharField(max_length=100, null=True)),
                ('lName', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=7, null=True)),
                ('dep', models.CharField(max_length=100, null=True)),
                ('section', models.CharField(max_length=2, null=True)),
                ('year', models.CharField(default='1st', max_length=5)),
                ('semi', models.CharField(default='1st', max_length=5)),
                ('DOB', models.DateField(null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('subcity', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('woreda', models.CharField(max_length=100, null=True)),
                ('kebele', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('grade8', models.FileField(null=True, upload_to='pdf_files/')),
                ('grade9_10', models.FileField(null=True, upload_to='pdf_files/')),
                ('grade10', models.FileField(null=True, upload_to='pdf_files/')),
                ('grade11_12', models.FileField(null=True, upload_to='pdf_files/')),
                ('grade12', models.FileField(null=True, upload_to='pdf_files/')),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100, null=True)),
                ('mName', models.CharField(max_length=100, null=True)),
                ('stuid', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('evid', models.FileField(null=True, upload_to='pdf_files/')),
            ],
        ),
    ]
