# Generated by Django 4.2.1 on 2023-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='noGr',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
