# Generated by Django 4.2.1 on 2023-06-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_grade_grade_alter_grade_nogr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grpoint',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='noGr',
            field=models.FloatField(null=True),
        ),
    ]
