# Generated by Django 4.2.1 on 2023-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_grade_grade_alter_grade_grpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cummlative',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='semigrade',
            field=models.FloatField(null=True),
        ),
    ]
