# Generated by Django 4.2.1 on 2023-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_cummlative_grade_cumulative'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='section',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
