# Generated by Django 4.2.1 on 2023-06-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_grade_section_alter_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='lName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='section',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='stuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
