# Generated by Django 4.2.1 on 2023-06-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_withdraw_lname_alter_grade_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='year',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
