# Generated by Django 4.2.1 on 2023-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_withdraw_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
