# Generated by Django 4.2.1 on 2023-06-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_withdraw_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
