# Generated by Django 4.2.2 on 2023-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_assign_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade11_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade8',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade9_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='college',
            name='passwd',
            field=models.CharField(default='collegeid', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='passwd',
            field=models.CharField(default='depid', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='passwd',
            field=models.CharField(default='insid', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='passwd',
            field=models.CharField(default='regid', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passwd',
            field=models.CharField(default='pbkdf2_sha256$600000$z4jRm1GUpYX4x9zPznA6Vb$IDS7WOZroFxcbgLKNOwnUGC/ek9d2sgMM5bMED+fkQw=', max_length=100, null=True),
        ),
    ]
