# Generated by Django 4.2.2 on 2023-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_grade_collapproval_alter_college_passwd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cummlative',
        ),
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AlterField(
            model_name='college',
            name='collegeid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='depid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='insid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='regid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
