# Generated by Django 4.2.2 on 2023-06-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_cummlative_remove_college_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='dep',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
