# Generated by Django 4.2.2 on 2023-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_assign_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='dep',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
