# Generated by Django 4.2.2 on 2023-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_assign_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='ccode',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='sid',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
