# Generated by Django 4.2.2 on 2023-06-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_grade_ccode_alter_grade_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='ccode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='sid',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
