# Generated by Django 4.2.2 on 2023-06-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_grade_ccode_alter_grade_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cumulative',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semigrade',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
