# Generated by Django 4.2.2 on 2023-06-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_grade_cumulative_alter_grade_semigrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grpoint',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='noGr',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
