# Generated by Django 4.2.2 on 2023-06-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_grade_grpoint_alter_grade_nogr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cumulative',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grpoint',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='noGr',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semigrade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
